# Generated by Django 2.2 on 2018-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0022_auto_20180916_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
