# Generated by Django 2.2 on 2018-09-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0023_studies_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='nonrisk/media/'),
        ),
    ]
