# Generated by Django 2.1 on 2018-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0031_pacient_arterial_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='race',
            field=models.CharField(blank=True, choices=[('W', 'white'), ('B', 'black')], max_length=1, null=True),
        ),
    ]
