# Generated by Django 2.1 on 2018-11-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0033_studies_renal_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='race',
            field=models.CharField(choices=[('W', 'white'), ('B', 'black')], default='W', max_length=1),
            preserve_default=False,
        ),
    ]
