# Generated by Django 2.1 on 2018-11-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0035_auto_20181105_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='ac_uric',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studies',
            name='creat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studies',
            name='hba1c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studies',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studies',
            name='pcr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studies',
            name='tsh',
            field=models.FloatField(),
        ),
    ]
