# Generated by Django 2.1 on 2018-09-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_second', models.CharField(blank=True, max_length=50)),
                ('name_last', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=175)),
                ('phone', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('medical_details', models.CharField(max_length=300)),
                ('smoke', models.BooleanField()),
                ('smoke_quantity', models.IntegerField()),
                ('smoke_duration', models.DateField()),
                ('smoke_quit', models.DateField()),
                ('diabetes', models.IntegerField()),
                ('diabetes_chol_level', models.IntegerField()),
                ('diabetes_hdl_level', models.IntegerField()),
                ('diabetes_ldl_level', models.IntegerField()),
                ('diabetes_tri_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('territory', models.CharField(choices=[('SYM', 'Symptomatic'), ('ASY', 'ASYMPTOMATIC')], max_length=3)),
                ('carotid_1', models.BooleanField()),
                ('carotid_2', models.BooleanField()),
                ('carotid_3', models.BooleanField()),
                ('carotid_4', models.BooleanField()),
                ('vertebrobasilar_1', models.BooleanField()),
                ('vertebrobasilar_2', models.BooleanField()),
                ('vertebrobasilar_3', models.BooleanField()),
                ('vertebrobasilar_4', models.BooleanField()),
                ('vertebrobasilar_5', models.BooleanField()),
                ('vertebrobasilar_6', models.BooleanField()),
                ('nonspecific_1', models.BooleanField()),
                ('nonspecific_2', models.BooleanField()),
                ('nonspecific_3', models.BooleanField()),
                ('nonspecific_4', models.BooleanField()),
                ('comments', models.CharField(max_length=300)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonrisk.Pacient')),
            ],
        ),
    ]
