# Generated by Django 2.1 on 2018-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='diabetes_type',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacient',
            name='diabetes',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='diabetes_chol_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='diabetes_hdl_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='diabetes_ldl_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='diabetes_tri_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='smoke_duration',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='smoke_quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='smoke_quit',
            field=models.DateField(blank=True),
        ),
    ]
