# Generated by Django 2.1 on 2018-09-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0004_auto_20180912_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
