# Generated by Django 2.1 on 2018-09-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0008_auto_20180914_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='diabetes_type',
            field=models.IntegerField(blank=True),
        ),
    ]
