# Generated by Django 2.1 on 2018-09-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0009_auto_20180914_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='diabetes_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='dislipidemia_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='hyper_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='smoke_duration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='smoke_quit',
            field=models.DateField(null=True),
        ),
    ]
