# Generated by Django 2.1 on 2018-09-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0012_auto_20180914_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='smoke_duration',
            field=models.DateField(null=True),
        ),
    ]
