# Generated by Django 2.1 on 2018-09-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0014_auto_20180915_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='diabetes_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='dislipidemia_type',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('IIa', 'IIa'), ('IIb', 'IIb'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='hyper_type',
            field=models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='irc_type',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3a', 'G3a'), ('G3b', 'G3b'), ('G4', 'G4'), ('G5', 'G5')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='smoke_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='diabetes_chol_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='diabetes_hdl_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='diabetes_ldl_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='diabetes_tri_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
