# Generated by Django 2.1 on 2018-09-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0015_auto_20180915_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='acv',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='acv_ait',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='diabetes_date',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='diabetes_type',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='dislipidemia',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='dislipidemia_date',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='dislipidemia_type',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='enfvp',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='fecvt',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='hyper',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='hyper_date',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='hyper_type',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='iam',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='irc',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='irc_type',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='revasc',
        ),
    ]
