# Generated by Django 2.1 on 2018-09-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0019_auto_20180915_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='hyper',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacient',
            name='hyper_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='hyper_type',
            field=models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=10, null=True),
        ),
    ]
