# Generated by Django 2.2 on 2018-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0025_auto_20180928_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Studies photo'),
        ),
    ]
