# Generated by Django 2.1 on 2018-10-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0026_auto_20180928_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='doctor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
