# Generated by Django 2.1 on 2018-10-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0027_pacient_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='studies',
            name='doctor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
