# Generated by Django 2.1 on 2018-10-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0028_auto_20181014_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studies',
            old_name='diabetes_chol_level',
            new_name='chol_level',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='diabetes_hdl_level',
            new_name='hdl_level',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='diabetes_ldl_level',
            new_name='ldl_level',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='diabetes_tri_level',
            new_name='tri_level',
        ),
    ]
