# Generated by Django 2.1 on 2018-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0003_auto_20180912_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
