# Generated by Django 2.1 on 2018-09-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0006_auto_20180913_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='irc_type',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3a', 'G3a'), ('G3b', 'G3b'), ('G4', 'G4'), ('G5', 'G5')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='irc',
            field=models.BooleanField(),
        ),
    ]
