# Generated by Django 2.1 on 2018-09-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0007_auto_20180913_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='dislipidemia_type',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('IIa', 'IIa'), ('IIb', 'IIb'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='hyper_type',
            field=models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=10),
        ),
    ]
