# Generated by Django 2.1 on 2018-09-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0018_auto_20180915_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='diabetes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacient',
            name='diabetes_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='diabetes_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
