# Generated by Django 2.1 on 2018-09-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonrisk', '0021_auto_20180915_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
